import { ChallengeTemplate, HabitCategory } from './types';

export const CHALLENGE_TEMPLATES: ChallengeTemplate[] = [
  {
    id: 'starter_habit_7_day',
    title: '7-Day Starter Habit Challenge',
    description: 'Complete one selected habit every day for 7 days.',
    category: 'all',
    durationDays: 7,
    requiredCompletionDays: 7,
    difficulty: 'hard',
    rewardXP: 300,
    rewardCoins: 1500,
    rewardBadgeId: 'seed_builder',
  },
  {
    id: 'first_garden_3_day',
    title: '3-Day First Garden Challenge',
    description: 'Complete any habit for 3 days to start your garden.',
    category: 'all',
    durationDays: 3,
    requiredCompletionDays: 3,
    difficulty: 'hard',
    rewardXP: 200,
    rewardCoins: 800,
    rewardBadgeId: 'first_garden',
  },
  {
    id: 'hydration_7_day',
    title: '7-Day Hydration Challenge',
    description: 'Complete Hydration habit every day.',
    category: 'hydration',
    durationDays: 7,
    requiredCompletionDays: 7,
    difficulty: 'hard',
    rewardXP: 300,
    rewardCoins: 1500,
    rewardBadgeId: 'hydration_hero',
    suggestedHabitName: 'Drink Water',
    suggestedPlantOptions: ['Coconut / Narikel', 'Watermelon / Tormuj'],
  },
  {
    id: 'study_garden_7_day',
    title: '7-Day Study Garden Challenge',
    description: 'Complete one Study habit daily for 7 days.',
    category: 'study',
    durationDays: 7,
    requiredCompletionDays: 5,
    difficulty: 'medium',
    rewardXP: 150,
    rewardCoins: 800,
    rewardBadgeId: 'study_garden',
    suggestedHabitName: 'Study Topic',
    suggestedPlantOptions: ['Mango / Aam', 'Black Plum / Jam'],
  },
  {
    id: 'fitness_7_day',
    title: '7-Day Fitness Challenge',
    description: 'Complete a Walking or Fitness habit every day.',
    category: 'fitness',
    durationDays: 7,
    requiredCompletionDays: 5,
    difficulty: 'medium',
    rewardXP: 150,
    rewardCoins: 800,
    rewardBadgeId: 'kathal_strength',
    suggestedHabitName: 'Fitness Workout',
    suggestedPlantOptions: ['Jackfruit / Kathal', 'Date Palm / Khejur'],
  },
  {
    id: 'sleep_better_7_day',
    title: '7-Day Sleep Better Challenge',
    description: 'Complete a Sleep or Rest habit every day.',
    category: 'sleep',
    durationDays: 7,
    requiredCompletionDays: 7,
    difficulty: 'hard',
    rewardXP: 350,
    rewardCoins: 1800,
    rewardBadgeId: 'sleep_moon',
    suggestedHabitName: 'Sleep 8 Hours',
    suggestedPlantOptions: ['Banana / Kola', 'Custard Apple / Ata'],
  },
  {
    id: 'reading_roots_7_day',
    title: '7-Day Reading Roots Challenge',
    description: 'Read a few pages or complete a Reading habit every day.',
    category: 'reading',
    durationDays: 7,
    requiredCompletionDays: 5,
    difficulty: 'medium',
    rewardXP: 120,
    rewardCoins: 600,
    rewardBadgeId: 'reading_roots',
    suggestedHabitName: 'Read A Book',
    suggestedPlantOptions: ['Mango / Aam', 'Fig / Dumur'],
  },
  {
    id: 'resilient_gardener_14_day',
    title: '14-Day Resilient Gardener Challenge',
    description: 'Complete one selected habit every day for 14 days.',
    category: 'all',
    durationDays: 14,
    requiredCompletionDays: 10,
    difficulty: 'medium',
    rewardXP: 300,
    rewardCoins: 1200,
    rewardBadgeId: 'seed_builder',
  },
  {
    id: 'blooming_habit_21_day',
    title: '21-Day Blooming Habit Challenge',
    description: 'Complete any habit consistently for 21 days to watch your garden bloom.',
    category: 'all',
    durationDays: 21,
    requiredCompletionDays: 18,
    difficulty: 'hard',
    rewardXP: 500,
    rewardCoins: 2500,
    rewardBadgeId: 'first_garden',
  },
  {
    id: 'legendary_orchard_30_day',
    title: '30-Day Legendary Orchard Challenge',
    description: 'Maintain a 30-day streak on any habit to gain immense rewards and legendary status.',
    category: 'all',
    durationDays: 30,
    requiredCompletionDays: 26,
    difficulty: 'hard',
    rewardXP: 1000,
    rewardCoins: 5000,
    rewardBadgeId: 'seed_builder',
  },
  {
    id: 'deep_study_14_day',
    title: '14-Day Deep Study Challenge',
    description: 'Complete a Study habit daily for 14 days to forge unbreakable focus.',
    category: 'study',
    durationDays: 14,
    requiredCompletionDays: 12,
    difficulty: 'medium',
    rewardXP: 400,
    rewardCoins: 1500,
    rewardBadgeId: 'study_garden',
    suggestedHabitName: 'Deep Study 2 Hours',
    suggestedPlantOptions: ['Mango / Aam', 'Black Plum / Jam'],
  },
  {
    id: 'iron_body_21_day',
    title: '21-Day Iron Body Challenge',
    description: 'Complete a Fitness habit every day for 21 days.',
    category: 'fitness',
    durationDays: 21,
    requiredCompletionDays: 18,
    difficulty: 'hard',
    rewardXP: 600,
    rewardCoins: 3000,
    rewardBadgeId: 'kathal_strength',
    suggestedHabitName: 'Intense Workout',
    suggestedPlantOptions: ['Jackfruit / Kathal', 'Date Palm / Khejur'],
  },
  {
    id: 'mindfulness_14_day',
    title: '14-Day Zen Mind Challenge',
    description: 'Meditate or practice mindfulness daily for 14 days.',
    category: 'mindfulness',
    durationDays: 14,
    requiredCompletionDays: 12,
    difficulty: 'medium',
    rewardXP: 300,
    rewardCoins: 1200,
    rewardBadgeId: 'first_garden',
    suggestedHabitName: 'Meditation',
    suggestedPlantOptions: ['Pineapple / Anaros', 'Indian Gooseberry / Amloki'],
  },
  {
    id: 'recovery_3_day',
    title: '3-Day Recovery Challenge',
    description: 'Complete a missed or wilting habit for 3 days to recover your garden.',
    category: 'recovery',
    durationDays: 3,
    requiredCompletionDays: 3,
    difficulty: 'hard',
    rewardXP: 250,
    rewardCoins: 1000,
    rewardBadgeId: 'plant_saver',
  }
];

export const getChallengeTemplate = (id: string) => CHALLENGE_TEMPLATES.find(c => c.id === id);
