import { ChallengeTemplate, HabitCategory } from './types';

export const CHALLENGE_TEMPLATES: ChallengeTemplate[] = [
  {
    id: 'starter_habit_7_day',
    title: '7-Day Starter Habit Challenge',
    description: 'Complete one selected habit every day for 7 days.',
    category: 'all',
    durationDays: 7,
    requiredCompletionDays: 5,
    difficulty: 'easy',
    rewardXP: 100,
    rewardCoins: 25,
    rewardBadgeId: 'seed_builder',
  },
  {
    id: 'first_garden_3_day',
    title: '3-Day First Garden Challenge',
    description: 'Complete any habit for 3 days to start your garden.',
    category: 'all',
    durationDays: 3,
    requiredCompletionDays: 2,
    difficulty: 'easy',
    rewardXP: 50,
    rewardCoins: 10,
    rewardBadgeId: 'first_garden',
  },
  {
    id: 'hydration_7_day',
    title: '7-Day Hydration Challenge',
    description: 'Complete Hydration habit every day.',
    category: 'hydration',
    durationDays: 7,
    requiredCompletionDays: 5,
    difficulty: 'easy',
    rewardXP: 100,
    rewardCoins: 25,
    rewardBadgeId: 'hydration_hero',
    suggestedHabitName: 'Drink Water',
    suggestedPlantOptions: ['Coconut / Narikel', 'Watermelon / Tormuj'],
  },
  {
    id: 'study_garden_7_day',
    title: '7-Day Study Garden Challenge',
    description: 'Complete one Study habit daily for 7 days.',
    category: 'study',
    durationDays: 7,
    requiredCompletionDays: 5,
    difficulty: 'medium',
    rewardXP: 150,
    rewardCoins: 40,
    rewardBadgeId: 'study_garden',
    suggestedHabitName: 'Study Topic',
    suggestedPlantOptions: ['Mango / Aam', 'Black Plum / Jam'],
  },
  {
    id: 'fitness_7_day',
    title: '7-Day Fitness Challenge',
    description: 'Complete a Walking or Fitness habit every day.',
    category: 'fitness',
    durationDays: 7,
    requiredCompletionDays: 5,
    difficulty: 'medium',
    rewardXP: 150,
    rewardCoins: 40,
    rewardBadgeId: 'kathal_strength',
    suggestedHabitName: 'Fitness Workout',
    suggestedPlantOptions: ['Jackfruit / Kathal', 'Date Palm / Khejur'],
  },
  {
    id: 'sleep_better_7_day',
    title: '7-Day Sleep Better Challenge',
    description: 'Complete a Sleep or Rest habit every day.',
    category: 'sleep',
    durationDays: 7,
    requiredCompletionDays: 5,
    difficulty: 'easy',
    rewardXP: 120,
    rewardCoins: 30,
    rewardBadgeId: 'sleep_moon',
    suggestedHabitName: 'Sleep 8 Hours',
    suggestedPlantOptions: ['Banana / Kola', 'Custard Apple / Ata'],
  },
  {
    id: 'reading_roots_7_day',
    title: '7-Day Reading Roots Challenge',
    description: 'Read a few pages or complete a Reading habit every day.',
    category: 'reading',
    durationDays: 7,
    requiredCompletionDays: 5,
    difficulty: 'medium',
    rewardXP: 120,
    rewardCoins: 30,
    rewardBadgeId: 'reading_roots',
    suggestedHabitName: 'Read A Book',
    suggestedPlantOptions: ['Mango / Aam', 'Fig / Dumur'],
  },
  {
    id: 'recovery_3_day',
    title: '3-Day Recovery Challenge',
    description: 'Complete a missed or wilting habit for 3 days to recover your garden.',
    category: 'recovery',
    durationDays: 3,
    requiredCompletionDays: 3,
    difficulty: 'easy',
    rewardXP: 80,
    rewardCoins: 20,
    rewardBadgeId: 'plant_saver',
  }
];

export const getChallengeTemplate = (id: string) => CHALLENGE_TEMPLATES.find(c => c.id === id);
