import { ShopItem } from './types';

export const SHOP_ITEMS: ShopItem[] = [
  {
    id: 'bg_default',
    name: 'Default Green Garden',
    type: 'background',
    price: 0,
    description: 'The standard green garden.',
    iconName: 'Layout',
  },
  {
    id: 'pot_clay_basic',
    name: 'Basic Clay Pot',
    type: 'pot',
    price: 30,
    description: 'A simple, traditional clay pot.',
    iconName: 'PackageOpen',
  },
  {
    id: 'pot_clay_colorful',
    name: 'Colorful Clay Pot',
    type: 'pot',
    price: 60,
    description: 'A painted pot inspired by local art.',
    iconName: 'Package',
  },
  {
    id: 'pot_bamboo_basket',
    name: 'Bamboo Basket Pot',
    type: 'pot',
    price: 80,
    description: 'A traditional woven bamboo basket.',
    iconName: 'Archive',
  },
  {
    id: 'pot_rooftop_tub',
    name: 'Rooftop Tub',
    type: 'pot',
    price: 100,
    description: 'A common half-drum rooftop tub.',
    iconName: 'Database',
  },
  {
    id: 'fence_bamboo',
    name: 'Bamboo Fence',
    type: 'fence',
    price: 80,
    description: 'A traditional bamboo fence for your garden.',
    iconName: 'AlignJustify',
  },
  {
    id: 'fence_wooden',
    name: 'Wooden Fence',
    type: 'fence',
    price: 100,
    description: 'A sturdy wooden fence border.',
    iconName: 'AlignJustify',
  },
  {
    id: 'fence_clay_wall',
    name: 'Clay Wall Border',
    type: 'fence',
    price: 120,
    description: 'A low earthen wall border around the plot.',
    iconName: 'Square',
  },
  {
    id: 'dec_fruit_basket',
    name: 'Fruit Basket',
    type: 'decoration',
    price: 70,
    description: 'A woven basket for your harvest.',
    iconName: 'ShoppingBasket',
  },
  {
    id: 'dec_mango_basket',
    name: 'Mango Basket',
    type: 'decoration',
    price: 120,
    description: 'A basket full of ripe mangos.',
    iconName: 'Apple',
  },
  {
    id: 'dec_butterfly',
    name: 'Butterfly',
    type: 'decoration',
    price: 90,
    description: 'A colorful butterfly visiting your garden.',
    iconName: 'Feather',
  },
  {
    id: 'dec_bird',
    name: 'Bird',
    type: 'decoration',
    price: 90,
    description: 'A small cheerful bird.',
    iconName: 'Twitter',
  },
  {
    id: 'dec_small_pond',
    name: 'Small Pond',
    type: 'decoration',
    price: 150,
    description: 'A small tranquil pond with water lilies.',
    iconName: 'Droplet',
  },
  {
    id: 'dec_clay_lamp',
    name: 'Clay Lamp',
    type: 'decoration',
    price: 100,
    description: 'A glowing traditional matir prodip.',
    iconName: 'Sun',
  },
  {
    id: 'dec_rickshaw_sign',
    name: 'Rickshaw Art Sign',
    type: 'decoration',
    price: 150,
    description: 'A colorful rickshaw art signboard.',
    iconName: 'Camera',
  },
  {
    id: 'dec_kolshi',
    name: 'Kolshi Water Pot',
    type: 'decoration',
    price: 100,
    description: 'A rounded pitcher for carrying water.',
    iconName: 'Coffee',
  },
  {
    id: 'bg_rooftop',
    name: 'Rooftop Garden',
    type: 'background',
    price: 150,
    description: 'A beautiful city rooftop garden background.',
    iconName: 'Building',
  },
  {
    id: 'bg_village',
    name: 'Village Garden',
    type: 'background',
    price: 200,
    description: 'A peaceful village garden background.',
    iconName: 'Home',
  },
  {
    id: 'bg_morning_sun',
    name: 'Morning Sun Garden',
    type: 'background',
    price: 180,
    description: 'A warm sunrise illuminating the garden.',
    iconName: 'Sun',
  },
  {
    id: 'bg_monsoon',
    name: 'Monsoon Garden',
    type: 'background',
    price: 220,
    description: 'A lush garden during the rainy season.',
    iconName: 'CloudRain',
  },
  {
    id: 'seasonal_boishakh',
    name: 'Boishakh Banner',
    type: 'seasonal',
    price: 300,
    description: 'A festive red and white banner.',
    iconName: 'Flag',
  },
  {
    id: 'seasonal_eid_lights',
    name: 'Eid Lights',
    type: 'seasonal',
    price: 300,
    description: 'Sparkling festive lights.',
    iconName: 'Zap',
  },
  {
    id: 'seasonal_ramadan_lantern',
    name: 'Ramadan Lantern',
    type: 'seasonal',
    price: 300,
    description: 'A beautiful crescent lantern.',
    iconName: 'Moon',
  },
  {
    id: 'seasonal_rain_cloud',
    name: 'Rain Cloud',
    type: 'seasonal',
    price: 250,
    description: 'A small shower cloud hovering above.',
    iconName: 'CloudRain',
  },
  {
    id: 'seasonal_winter_sun',
    name: 'Winter Sun',
    type: 'seasonal',
    price: 250,
    description: 'A gentle, warm winter sun.',
    iconName: 'Sun',
  },
  {
    id: 'boost_fertilizer',
    name: 'Fertilizer',
    type: 'boost',
    price: 40,
    description: '+20 Plant XP to one plant.',
    iconName: 'Sprout',
    isConsumable: true,
  },
  {
    id: 'boost_sunlight',
    name: 'Sunlight Boost',
    type: 'boost',
    price: 50,
    description: '+10 Bonus XP on next habit completion.',
    iconName: 'Sun',
    isConsumable: true,
  },
  {
    id: 'boost_rain',
    name: 'Rain Boost',
    type: 'boost',
    price: 60,
    description: 'Restores +10 health to all plants today.',
    iconName: 'CloudRain',
    isConsumable: true,
  },
  {
    id: 'boost_recovery_water',
    name: 'Recovery Water',
    type: 'boost',
    price: 70,
    description: 'Adds +20 health to a wilting or critical plant.',
    iconName: 'Droplets',
    isConsumable: true,
  }
];
